remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Siom P ]
description: [This is my Portfolio]
description: [I am a self-taught designer and autodidact learner. My aim is to transform practical design into solutions to social problems present in my community. I firmly believe that design applied as a way/method of thinking can approach an objective yet integrative way to add value to a service/product or goal.
Quantum mechanics, society and logic, and design are on the foundations of my interests and passion.]
