title: Siom Portfolio
#show downloads: true
theme: minima
email: mr.maclowelll@gmail.com
minima: 
skin: classic
github name: maclowelll

header pages: 
- about.md
home pages: 
- whyidesign.md
footer heading: 
- about.md
